services:
  php:
    build: ./php
    volumes:
      - ./www:/var/www/html
      - ./php-ini:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    ports:
      - 8080:80

  db:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
