services:
  php:
    build: .
    # restart: always
    volumes:
      - ./www:/var/www/example.com
      - ./log/apache2:/var/log/apache2
    ports:
      - 8082:80

  db:
    image: mysql:8.0
    # restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER: "user"
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_root_password

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 8083:80
    environment:
      PMA_ARBITRARY: 1

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
