services:
  php:
    build: .
    # restart: always
    volumes:
      - ./www:/var/www/html
      - ./php/conf.d:/usr/local/etc/php/conf.d
      - ./log/apache2:/var/log/apache2
    ports:
      - 8082:80

  db:
    image: mysql:8.0
    # restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 127.0.0.1:8083:80
    environment:
      PMA_ARBITRARY: 1

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./www:/var/www/html:rw
  #     - ./letsencrypt/conf:/etc/letsencrypt:rw
