services:
  php:
    build: .
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./php:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    ports:
      - 80:80

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "lIQPo^g;nbQ?U3ZwgtW"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./www:/var/www/html:rw
  #     - ./letsencrypt/conf:/etc/letsencrypt:rw
